language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=a9c690bed85729f9a7ac32a682c7c93494eaaccfea5f9d64459e6fd9ea621a6f
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=3e4829af097b12f4255e9b04fa27c408850a783f
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
    - BITS=64
  matrix:
    - UNUSED=true
    - TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32
    - TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=2c2cce54e3644950b350f2d798d15a9504216331
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=2c2cce54e3644950b350f2d798d15a9504216331 TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=2c2cce54e3644950b350f2d798d15a9504216331 TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=2c2cce54e3644950b350f2d798d15a9504216331 TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST $BITS"
